const CONVERSATION_STAGES = Object.freeze({
  ASK_VEHICLE: "ASK_VEHICLE",
  ASK_TIMING: "ASK_TIMING",
  ASK_INITIAL_CAPITAL: "ASK_INITIAL_CAPITAL",
  ASK_CITY: "ASK_CITY",
  CLOSE_MEETING: "CLOSE_MEETING"
});

module.exports = {
  CONVERSATION_STAGES
};
